# Generated by Django 2.1.5 on 2019-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20190706_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_detalle',
            name='cantidad',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='talla',
            field=models.SmallIntegerField(),
        ),
    ]
