# Generated by Django 2.1.5 on 2019-07-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20190706_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
