# Generated by Django 2.1.5 on 2019-07-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20190706_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='subcategoria',
            field=models.CharField(choices=[('business', 'business'), ('casual', 'casual'), ('chamarra', 'chamarra'), ('shoes', 'shoes'), ('tshirt', 'tshirt')], max_length=50),
        ),
    ]
