# Generated by Django 2.2.3 on 2019-07-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20190706_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
